
package com.elm.yakeen.yakeen4borderguard;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Yakeen4BorderGuard", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Yakeen4BorderGuard {


    /**
     * 
     * @param visitorInfoByBorderNumberRequest
     * @return
     *     returns com.elm.yakeen.yakeen4borderguard.VisitorInfoByBorderNumberResult
     * @throws Yakeen4BorderGuardFault_Exception
     */
    @WebMethod
    @WebResult(name = "VisitorInfoByBorderNumberResult", targetNamespace = "")
    @RequestWrapper(localName = "getVisitorInfoByBorderNumber", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", className = "com.elm.yakeen.yakeen4borderguard.GetVisitorInfoByBorderNumber")
    @ResponseWrapper(localName = "getVisitorInfoByBorderNumberResponse", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", className = "com.elm.yakeen.yakeen4borderguard.GetVisitorInfoByBorderNumberResponse")
    public VisitorInfoByBorderNumberResult getVisitorInfoByBorderNumber(
        @WebParam(name = "VisitorInfoByBorderNumberRequest", targetNamespace = "")
        VisitorInfoByBorderNumberRequest visitorInfoByBorderNumberRequest)
        throws Yakeen4BorderGuardFault_Exception
    ;

    /**
     * 
     * @param gccInfoByPassportRequest
     * @return
     *     returns com.elm.yakeen.yakeen4borderguard.GccInfoByPassportResult
     * @throws Yakeen4BorderGuardFault_Exception
     */
    @WebMethod
    @WebResult(name = "GCCInfoByPassportResult", targetNamespace = "")
    @RequestWrapper(localName = "getGCCInfoByPassport", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", className = "com.elm.yakeen.yakeen4borderguard.GetGCCInfoByPassport")
    @ResponseWrapper(localName = "getGCCInfoByPassportResponse", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", className = "com.elm.yakeen.yakeen4borderguard.GetGCCInfoByPassportResponse")
    public GccInfoByPassportResult getGCCInfoByPassport(
        @WebParam(name = "GCCInfoByPassportRequest", targetNamespace = "")
        GccInfoByPassportRequest gccInfoByPassportRequest)
        throws Yakeen4BorderGuardFault_Exception
    ;

    /**
     * 
     * @param citizenInfoRequest
     * @return
     *     returns com.elm.yakeen.yakeen4borderguard.CitizenInfoResult
     * @throws Yakeen4BorderGuardFault_Exception
     */
    @WebMethod
    @WebResult(name = "CitizenInfoResult", targetNamespace = "")
    @RequestWrapper(localName = "getCitizenInfo", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", className = "com.elm.yakeen.yakeen4borderguard.GetCitizenInfo")
    @ResponseWrapper(localName = "getCitizenInfoResponse", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", className = "com.elm.yakeen.yakeen4borderguard.GetCitizenInfoResponse")
    public CitizenInfoResult getCitizenInfo(
        @WebParam(name = "CitizenInfoRequest", targetNamespace = "")
        CitizenInfoRequest citizenInfoRequest)
        throws Yakeen4BorderGuardFault_Exception
    ;

    /**
     * 
     * @param residentInfoByIqamaRequest
     * @return
     *     returns com.elm.yakeen.yakeen4borderguard.ResidentInfoByIqamaResult
     * @throws Yakeen4BorderGuardFault_Exception
     */
    @WebMethod
    @WebResult(name = "ResidentInfoByIqamaResult", targetNamespace = "")
    @RequestWrapper(localName = "getResidentInfoByIqama", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", className = "com.elm.yakeen.yakeen4borderguard.GetResidentInfoByIqama")
    @ResponseWrapper(localName = "getResidentInfoByIqamaResponse", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", className = "com.elm.yakeen.yakeen4borderguard.GetResidentInfoByIqamaResponse")
    public ResidentInfoByIqamaResult getResidentInfoByIqama(
        @WebParam(name = "ResidentInfoByIqamaRequest", targetNamespace = "")
        ResidentInfoByIqamaRequest residentInfoByIqamaRequest)
        throws Yakeen4BorderGuardFault_Exception
    ;

    /**
     * 
     * @param carInfoByPlateRequest
     * @return
     *     returns com.elm.yakeen.yakeen4borderguard.CarInfoByPlateResult
     * @throws Yakeen4BorderGuardFault_Exception
     */
    @WebMethod
    @WebResult(name = "CarInfoByPlateResult", targetNamespace = "")
    @RequestWrapper(localName = "getCarInfoByPlate", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", className = "com.elm.yakeen.yakeen4borderguard.GetCarInfoByPlate")
    @ResponseWrapper(localName = "getCarInfoByPlateResponse", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", className = "com.elm.yakeen.yakeen4borderguard.GetCarInfoByPlateResponse")
    public CarInfoByPlateResult getCarInfoByPlate(
        @WebParam(name = "CarInfoByPlateRequest", targetNamespace = "")
        CarInfoByPlateRequest carInfoByPlateRequest)
        throws Yakeen4BorderGuardFault_Exception
    ;

    /**
     * 
     * @param gccInfoByNINRequest
     * @return
     *     returns com.elm.yakeen.yakeen4borderguard.GccInfoByNINResult
     * @throws Yakeen4BorderGuardFault_Exception
     */
    @WebMethod
    @WebResult(name = "GCCInfoByNINResult", targetNamespace = "")
    @RequestWrapper(localName = "getGCCInfoByNIN", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", className = "com.elm.yakeen.yakeen4borderguard.GetGCCInfoByNIN")
    @ResponseWrapper(localName = "getGCCInfoByNINResponse", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", className = "com.elm.yakeen.yakeen4borderguard.GetGCCInfoByNINResponse")
    public GccInfoByNINResult getGCCInfoByNIN(
        @WebParam(name = "GCCInfoByNINRequest", targetNamespace = "")
        GccInfoByNINRequest gccInfoByNINRequest)
        throws Yakeen4BorderGuardFault_Exception
    ;

}
