
package com.elm.yakeen.yakeen4borderguard;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Yakeen4BorderGuardFault", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/")
public class Yakeen4BorderGuardFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Yakeen4BorderGuardFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Yakeen4BorderGuardFault_Exception(String message, Yakeen4BorderGuardFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Yakeen4BorderGuardFault_Exception(String message, Yakeen4BorderGuardFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.elm.yakeen.yakeen4borderguard.Yakeen4BorderGuardFault
     */
    public Yakeen4BorderGuardFault getFaultInfo() {
        return faultInfo;
    }

}
