
package com.elm.yakeen.yakeen4borderguard;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Yakeen4BorderGuardService", targetNamespace = "http://yakeen4borderguard.yakeen.elm.com/", wsdlLocation = "http://yakeen-piloting.eserve.com.sa/Yakeen4BorderGuard/Yakeen4BorderGuard?wsdl")
public class Yakeen4BorderGuardService
    extends Service
{

    private final static URL YAKEEN4BORDERGUARDSERVICE_WSDL_LOCATION;
    private final static WebServiceException YAKEEN4BORDERGUARDSERVICE_EXCEPTION;
    private final static QName YAKEEN4BORDERGUARDSERVICE_QNAME = new QName("http://yakeen4borderguard.yakeen.elm.com/", "Yakeen4BorderGuardService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://yakeen-piloting.eserve.com.sa/Yakeen4BorderGuard/Yakeen4BorderGuard?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        YAKEEN4BORDERGUARDSERVICE_WSDL_LOCATION = url;
        YAKEEN4BORDERGUARDSERVICE_EXCEPTION = e;
    }

    public Yakeen4BorderGuardService() {
        super(__getWsdlLocation(), YAKEEN4BORDERGUARDSERVICE_QNAME);
    }

    public Yakeen4BorderGuardService(WebServiceFeature... features) {
        super(__getWsdlLocation(), YAKEEN4BORDERGUARDSERVICE_QNAME, features);
    }

    public Yakeen4BorderGuardService(URL wsdlLocation) {
        super(wsdlLocation, YAKEEN4BORDERGUARDSERVICE_QNAME);
    }

    public Yakeen4BorderGuardService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, YAKEEN4BORDERGUARDSERVICE_QNAME, features);
    }

    public Yakeen4BorderGuardService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Yakeen4BorderGuardService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Yakeen4BorderGuard
     */
    @WebEndpoint(name = "Yakeen4BorderGuardPort")
    public Yakeen4BorderGuard getYakeen4BorderGuardPort() {
        return super.getPort(new QName("http://yakeen4borderguard.yakeen.elm.com/", "Yakeen4BorderGuardPort"), Yakeen4BorderGuard.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Yakeen4BorderGuard
     */
    @WebEndpoint(name = "Yakeen4BorderGuardPort")
    public Yakeen4BorderGuard getYakeen4BorderGuardPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://yakeen4borderguard.yakeen.elm.com/", "Yakeen4BorderGuardPort"), Yakeen4BorderGuard.class, features);
    }

    private static URL __getWsdlLocation() {
        if (YAKEEN4BORDERGUARDSERVICE_EXCEPTION!= null) {
            throw YAKEEN4BORDERGUARDSERVICE_EXCEPTION;
        }
        return YAKEEN4BORDERGUARDSERVICE_WSDL_LOCATION;
    }

}
